### PR TITLE
Improve AntiBlackOut From Neutral Killers/Covens

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
wait did you just, do it yourself?

**Comment by Tommy-XL** [comment]
Yes

**Comment by Tommy-XL** [comment]
Oh, wait, i noticed a bug

**Comment by Loonie-Toons** [comment]
lol

**Comment by Loonie-Toons** [comment]
Also could do the system message for substituting the custom ejection, since I have no idea how to do that lol

**Comment by Tommy-XL** [comment]
Where is my fix bugs ._.

**Pull request closed without merging**
