### PR TITLE
Improve NotifyRoles (for seer) & Change Medic Mark

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Since there is a lot of code repetition in the conditions, why not reduce this code by only 1 check?

**Comment by ryuk201198** [comment]
@Tommy-XL that got me thinking if same can be done with CheckGameEndPatch.cs

**Comment by Tommy-XL** [comment]
I think can, because sometimes there is a repeated code that is checked in each condition

**Comment by Tommy-XL** [comment]
I'll work on improving for the target later

**Comment by Loonie-Toons** [comment]
I have uploaded the source code I did from last night, so please update this when you can lol.

**Comment by Tommy-XL** [comment]
?

**Comment by Tommy-XL** [comment]
No conflicts, its fine

**Comment by Tommy-XL** [comment]
I looked at the code changes in this PR and it doesn't remove anything from the uploaded code :/

**Comment by Tommy-XL** [comment]
Nothing has changed, lol
Screenshot_20230831_022829

**Pull request merged**
