### PR TITLE
"IsEnable" no longer depends on arrays

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by NikoCat233** [comment]
Can we add a temporary option set for non-host mod players  to save host's settings and delete after leaving the lobby

So player's own settings won't get changed or overwritten?

**Comment by vdpcool** [comment]
Lol.

**Comment by Tommy-XL** [comment]
It seems github is working again

**Comment by vdpcool** [comment]
Nice.

**Comment by Loonie-Toons** [comment]
yea

**Comment by vdpcool** [comment]
You'll close this after merge.

**Comment by Loonie-Toons** [comment]
Its considering closed after a merge

**Pull request merged**
