### PR TITLE
Fix Sheriff

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
amazing change
image

**Comment by Tommy-XL** [comment]
I just tried to fix the sabotage button, but it didn't work

**Comment by Loonie-Toons** [comment]
It's related to the fact that the host isn't an "Impostor".

Players that join with the mod can click it fine, as they're a desynced Impostor.

**Comment by Tommy-XL** [comment]
Yes, but the Jackal and other neutrals that can use sabotage cannot press the sabotage button

**Comment by Loonie-Toons** [comment]
Yea, that's what I explained.
They can't click it as the game considers them as a crewmate basis, thus not allowing them to click the sabotage button.

In order to fix this, the host would need to be desynced much like in Lotus.

**Comment by Loonie-Toons** [comment]
I attempted it, it didn't go well.
image

**Comment by Tommy-XL** [comment]
Just checked in TOH, everything works fine there

**Comment by Loonie-Toons** [comment]
Hm, odd.

**Comment by Tommy-XL** [comment]
I found out the cause of the bug, lol

**Comment by Loonie-Toons** [comment]
Lol, what's the cause?

**Comment by Tommy-XL** [comment]
You'll know soon

**Pull request merged**
