### PR TITLE
Fix Some Neutrals Can't Use Sabotage Button

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Tommy-XL** [comment]
I noticed a bug that needs to be fixed

**Comment by Loonie-Toons** [comment]
Yea, and I've noticed you made these four roles no longer desynced (causing vanilla players to spawn as a crewmate basis)
image

**Comment by Loonie-Toons** [comment]
Along with these four

image

**Comment by Tommy-XL** [comment]
Hmm, then I don't know how to fix it, xd

**Comment by Loonie-Toons** [comment]
lol

**Pull request closed without merging**
