### PR TITLE
Fix Egoist Win Screen

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
The change you made makes it so Egoists no longer win together.
Egoists will instead only solo win.

**Comment by Tommy-XL** [comment]
Fixed
image

image

**Comment by Loonie-Toons** [comment]
Now just to make sure, does an Egoist Crewmate win with an Egoist Impostor (and vice versa)? I had it like this.

**Comment by Tommy-XL** [comment]
No, before this they couldn’t win together either, since they were stealing the victory from their team

**Comment by Loonie-Toons** [comment]
Well before, if there were two Egoist Impostors (or two Egoist Crewmates), only the Egoist with the highest player ID would win.

I had changed this so all Egoist would win together if at least one Egoist stole the win.

With this change, it's now team dependent.

**Comment by Tommy-XL** [comment]
...

**Comment by Loonie-Toons** [comment]
Internet is too slow to merge atm

**Comment by Tommy-XL** [comment]
I closed it because I would have to rewrite the code, but I don't have time for that yet

**Comment by Loonie-Toons** [comment]
Mmk, this will have to do for now since I have a role to port from Gurge's fork that uses this file.

**Pull request merged**
