### PR TITLE
Added void ballot and Aware and changes in oracle

### PR DESCRIPTION
**Pull request by ryuk201198**
1. Added Void ballot and made it incompatible with glitch
2. Added Aware
3. Made it so that roles doesnt need to be added for oracle checks

### CODE REVIEW

**Comment by ryuk201198** [comment]
Fixed a bug in inspector and made it so that Admired are counted as crew

**Comment by Loonie-Toons** [comment]
I've handled the role changes already, I'll get to the new content within the next day or two.

**Comment by ryuk201198** [comment]
Added Frafile addon

**Comment by ryuk201198** [comment]
fragile*

**Pull request closed without merging**
