### PR TITLE
Role Summary Default On

### PR DESCRIPTION
**Pull request by Tommy-XL**
Why its off by default?

### CODE REVIEW

**Comment by Tommy-XL** [comment]
...

**Comment by Loonie-Toons** [comment]
I believe I had it off by default to reduce load, but can be toggled back on if the user so desired.

**Comment by Tommy-XL** [comment]
I don't think it has any effect on load as the Role Summary only fires at the end of the game (I also need to work on reduce load)

**Comment by Loonie-Toons** [comment]
Well another reason why I did it is because I wanna make the end screen centered like how it used to be, but I'd also have to rework the end game summary to be smaller and more compact.

I basically want it to look like how it is in Town of Us Reactivated, but with changes to account for the additional data TOH-RE has.

**Comment by Tommy-XL** [comment]
Well, I hope that the old one will remain in the form of a client setting (because I don’t really like the result of playing ToU-R)

**Comment by Loonie-Toons** [comment]
That's the plan with the setting, its just a placeholder.
Only issue is that I do not understand how the results are displayed, or how to change it.

**Pull request merged**
