### PR TITLE
Allow some roles to see others' addons

### PR DESCRIPTION
**Pull request by NikoCat233**
1.Add settings for god/lovers to see others/other lovers' addons
2.Change traget -> target
3.Turn else if in showroletarget so we won't miss conditions (thought its slower but it wont miss stuffs)
4.Update mark append  ♥ for the change
5.correct codes in GetRoleText so i can actually use "bool pure"
6.bool pure is now decided by ShowRoleAddonsTarget

wow there is a roletext in utils for non mod players
a roletext in meeting hud for local player
and a roletext in playercontrol for local player in game

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Isn't it smart to use "else if"? (since one of the conditions will return true and after that it will still check other conditions)
image

**Comment by Tommy-XL** [comment]
From a performance point of view this is not very good code

**Comment by NikoCat233** [comment]
Sorry
Again I misunderstood the codes

**Comment by NikoCat233** [comment]
I meet new bugs when I change if to else if

**Comment by Loonie-Toons** [comment]
Can you or anyone else confirm this works?

**Comment by NikoCat233** [comment]
I use mci and this works as host
I did not check for real game

**Comment by Tommy-XL** [comment]
Looking at the code, there is a suspicion of bugs, I think this code should be added after the release of 3.0.0

**Comment by NikoCat233** [comment]
There are tons of bugs =-=

**Pull request closed without merging**
