### PR TITLE
Small improve for EAC

### PR DESCRIPTION
**Pull request by NikoCat233**
1. Allow checks for android and mac (Why we ignore these clients?)
2. Handle all cheats detected by EAC (Why only report and the EAC.cloud is broken?)
3. Improve reportdeadbodycheck (The callmeeting checks is useless now cause clients all use reportdeadbody now)
4. Fix wrong translation (WTF ban and kick misplaces for so long?)

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
Mac is an unused platform in the code.

**Comment by Loonie-Toons** [comment]
also i dont see a reason for this

**Comment by NikoCat233** [comment]
> also i dont see a reason for this

I use this to fight spam meeting hacks on public server. =(

**Comment by Loonie-Toons** [comment]
We can't even go public due to the protocol.
There is no reason for this.

**Pull request closed without merging**
