### PR TITLE
Add option: Allow this room to be public

### PR DESCRIPTION
**Pull request by LezaiYa**

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
I'm specifically gonna deny this due to the fact that people will enable this then complain over roles not working.

**Comment by LezaiYa** [comment]
> I'm specifically gonna deny this due to the fact that people will enable this then complain over roles not working.

I know that enabling this will cause a lot of Roles to be unusable, but it can be turned off in the options

**Comment by LezaiYa** [comment]
Making some Roles work

**Comment by ryuk201198** [comment]
If you want this option, i'd rather say you edit OptionHolder.cs so that broken roles don't show up. Although i dont really see a point in this 🤷🏻

**Comment by LezaiYa** [comment]
> If you want this option, i'd rather suggest you edit OptionHolder.cs so that broken roles don't show up. Although i dont really see a point in this 🤷🏻

Mainly because there's usually not a lot of people to play with, so you have to look for people in the lobby, and the added protocols make the rooms unavailable to the public

**Comment by vdpcool** [comment]
Idea is Make Public option but the code to work is NewString.json. )))))

**Comment by LezaiYa** [comment]
> Idea is Make Public option but the code to work is NewString.json. )))))

image
I've added it. )))))

**Comment by vdpcool** [comment]
> > Idea is Make Public option but the code to work is NewString.json. )))))
> 
> image I've added it. )))))

xd. ))))

**Pull request closed without merging**
