### PR TITLE
Small security improvement

### PR DESCRIPTION
**Pull request by Gurge44**
You will thank me for this in the future

### CODE REVIEW

**Comment by aaronliu0130** [comment]
You simply un-const'd an object and removed god mode from the devs for no reason. I strongly suspect this will not be merged.

**Comment by Loonie-Toons** [comment]
Yea, the whole reason is to make devs unbannable.

**Comment by Gurge44** [comment]
I stg none of you get the point of making devs unbannable..... if the friend code spoofing is patched in the future, hackers will be able to use these unbannable friend codes to bypass the EAC.... and the EAC list being readonly means it cannot be expanded, which means hackers won't be banned.......... This was said by someone who knows C# deeply enough, so the fact that you're denying it is just worrying
@aaronliu0130 Yes, simply "un-const-ing" a variable can cause serious issues, and just because VS suggests it to be readonly, it doesn't mean it will be good
@Loonie-Toons Well I guess you don't want to improve the security of your mod in the future, which is the reason why most people don't like TOHE; the hackers are able to see the source code and find security breaches in it, so if you straight up make a friend code that bypasses everything, that's like asking a hacker to abuse it
Your choice

**Comment by aaronliu0130** [comment]
I do not know what method you mean by "friend code spoofing". I found no such thing online and I doubt your average vandal who's bored enough to disrupt a modded among us lobby would be able to find it.
The general rule of thumb is if a variable doesn't have any possibility of being reassigned you should make it read-only. All operations to this variable are just methods, never reassignment.

**Pull request closed without merging**
