### PR TITLE
Fix Loonie's mistakes & Random Spawns not working on Polus

### PR DESCRIPTION
**Pull request by Gurge44**
Yes I literally undid the banmanager stuff because Loonie still doesn't understand the risk of it

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
And as such, I won't be merging this

**Comment by Loonie-Toons** [comment]
Because its better with it in place

**Comment by Gurge44** [comment]
So random spawns will never work on Polus or will you copy-paste those 3 lines into IntroPatch.cs?

**Comment by aaronliu0130** [comment]
@Loonie-Toons they mean that they started their branch without the ban exceptions and then undid that (why not just start a new branch) so now the ban exception for devs is still there

**Comment by aaronliu0130** [comment]
there's also a merge conflict with 37e3f7d

**Comment by ryuk201198** [comment]
@aaronliu0130 we need to remove the ban exceptions because it makes the job of hackers easier. 😕

**Comment by aaronliu0130** [comment]
I have yet to see evidence of spoofing an existing friend code

**Comment by ryuk201198** [comment]
@aaronliu0130 loonie knows abt it. I do have Some ss for it too

**Comment by Loonie-Toons** [comment]
@aaronliu0130 I have access to friend code spoofing. I was able to spoof mine to "loonietoons".

**Comment by Tommy-XL** [comment]
Wouldn't it be better to find a way to force players with a fake friend code to be kicked out of the lobby?

**Comment by Gurge44** [comment]
Yeah but how do we know if a friend code is fake....

**Pull request closed without merging**
