### PR TITLE
Add fategiver

### PR DESCRIPTION
**Pull request by NikoCat233**
Fategiver from TOHEX
But reworked , fixed bugs, add customize settings, With fun strings.
https://discord.com/channels/1094344790910455908/1144923461542744084

I already tested the role myself and it works fine. Pls help change the role id cause I set it randomly.

I make setupadtrole public so I can use it outside of option holder. (I make fategiver a single file so I won't mess up the codes)
(Why do we have to setup every adt role in optionholder and put their stuffs everywhere...)

### CODE REVIEW

**Comment by NikoCat233** [comment]
Lmao I used format on newstring.json

**Comment by NikoCat233** [comment]
中文翻译者请注意，如果这个职业被采用了，请保留我的翻译。我的中文翻译完全是整活用的！

**Comment by LezaiYa** [comment]
这什么中文翻译啊，不过，我喜欢doge

**Comment by NikoCat233** [comment]
GG for not getting merged

**Pull request closed without merging**
